### ISSUE TITLE
Link existing sample instance

### ISSUE THREAD

**Issue by nichtich** [hbz/skohub-vocabs#40]
README tells a fork can be made public at <https://test.skohub.io/YOUR_GITHUB_USER/skos/w3id.org/class/hochschulfaecher/scheme>. It would help to also link to an existing instance. <https://test.skohub.io/hbz/skos/w3id.org/class/hochschulfaecher/scheme> does not exist.

**Comment by acka47** [comment]
You can publish from any GitHub repo that contains at least one SKOS scheme in turtle format, see e.g. https://test.skohub.io/hbz/vocabs-edu/.  For the process, see https://github.com/lobid/lobid.github.com/blob/skohub-endOfProject1/_posts/2019-09-18-skohub-prototype.md#publishing-a-controlled-vocabulary-with-skohhub-static-site-generator (which is a draft post to be reworked and split up in three separate posts). I will send you the secret for setting up a webhook via another channel.

**Comment by acka47** [comment]
I hope the uncertainties are clarified with the blog post at http://blog.lobid.org/2019/09/27/presenting-skohub-vocabs.html. Closing.
