### ISSUE TITLE
Set up staging and production environment

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-vocabs#44]
Until now, we've been happy with only one deployment environment running on https://test.skohub.io. It is time to switch to both a test and production environment with produvtion running on https://skohub.io.

**Comment by literarymachine** [comment]
Mirrored all current deployments to production, see

- https://skohub.io/literarymachine/skos/
- https://skohub.io/editor/
- https://skohub.io/deck/
- https://skohub.io/build (webhook)

**Comment by acka47** [comment]
+1 Closing.
