### ISSUE TITLE
Support deployment per git branch / tag

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-vocabs#45]
All commit pointers (branches or tags) from a repository should be published via SkoHub.

**Comment by literarymachine** [comment]
On test, see e.g. https://test.skohub.io/literarymachine/skos/test/purl.org/dcx/lrmi-vocabs/educationalAudienceRole/

**Comment by literarymachine** [comment]
@acka47 currently, only branches are built. The branch name becomes part of the URL, e.g. `test` in 
https://test.skohub.io/literarymachine/skos/test/purl.org/dcx/lrmi-vocabs/interactivityType/index.html

If we include tags in the same URL pattern, we will potentially run into conflicts. You can create a `tag` with the same name as a `branch`:

```
$ git checkout -b test 
Switched to a new branch 'test'
$ git branch
  master
* test
$ git tag test
$ git tag
test
```

In the current URL pattern, one would overwrite the other. How should we resolve this? We could of course add the type of `ref` to the URL, e.g. `/heads/test` and `/tags/test`, but I am wondering if this bloats the URLs to much?

**Comment by acka47** [comment]
+1
