### ISSUE TITLE
Problem with multiple RDF types

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-vocabs#55]
See https://test.skohub.io/build/?id=0f71e7ef-98b4-4fc6-9e84-3332fe2bf62e#68 for https://github.com/hbz/lobid-vocabs. There are some SKOS files contained in folders which might also be a problem.

**Comment by literarymachine** [comment]
> There are some SKOS files contained in folders which might also be a problem.

I don't think this causes problems - from a git perspective, there is no such thing as a "folder".

> See https://test.skohub.io/build/?id=0f71e7ef-98b4-4fc6-9e84-3332fe2bf62e#68 for https://github.com/hbz/lobid-vocabs.

The problem here seams to be that in https://github.com/hbz/lobid-vocabs/blob/master/lobid-vocab.ttl multiple `rdf:type` are used.
