### ISSUE TITLE
Highlight links

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-vocabs#57]
With the current, you can not see whether something is a link, see e.g. https://skohub.io/dini-ag-kim/hochschulfaechersystematik/w3id.org/class/hochschulfaechersystematik/scheme.html or https://skohub.io. I suggest making them blue as people are used to.

**Comment by literarymachine** [comment]
On test, see e.g. https://test.skohub.io/literarymachine/skos/test/w3id.org/class/hochschulfaecher/scheme.html

**Comment by acka47** [comment]
Looks god for the link you provided but https://test.skohub.io/ has not improved.

**Comment by literarymachine** [comment]
@dobladov please also apply the styles to https://skohub.io/

**Comment by literarymachine** [comment]
> Looks god for the link you provided but https://test.skohub.io/ has not improved.

Fixed, see https://skohub.io/ and https://test.skohub.io/

**Comment by acka47** [comment]
+1
