### ISSUE TITLE
Show link to vocab file in repo

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-vocabs#59]
E.g. with GitHub or GitLab icon.

**Comment by literarymachine** [comment]
On test, see e.g. https://test.skohub.io/literarymachine/skos/test/w3id.org/class/hochschulfaecher/scheme.html

**Comment by acka47** [comment]
I think it should better read "Fork this vocab on GitHub" to not confuse between software and vocabs.

**Comment by acka47** [comment]
+1
