### ISSUE TITLE
No access to SkoHub build information

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-vocabs#78]
This only refers to the version on lobid servers. Example link: https://skohub.lobid.org/build/?id=d7649625-b911-410b-a227-170288a335e2

At skohub.io I can view the build information.

**Comment by acka47** [comment]
I can also not access the vocab itself, compare https://skohub.lobid.org/acka47/lrmi-resource-types/heads/master/purl.org/dcx/lrmi-vocabs/learningResourceType/index.html with https://skohub.io/acka47/lrmi-resource-types/heads/master/purl.org/dcx/lrmi-vocabs/learningResourceType/index.html

**Comment by dr0i** [comment]
Fix by `ProxyPass /  /gaia/skohub-vocabs`  and enabling the webserver at gaia, point to `/home/lod/git/skohub-vocabs/dist`.
