### ISSUE TITLE
Inbox links point to wrong URL

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-vocabs#81]
[Reported by Raphaëlle via Mastodon.](https://mamot.fr/@rlapotre/104166783175808991)

See e.g. https://skohub.io/dini-ag-kim/hochschulfaechersystematik/heads/master/w3id.org/kim/hochschulfaechersystematik/n1.html

"Inbox" links to a URL at skohub.lobid.org, should be skohub.io.

**Comment by dr0i** [comment]
These were build at ` May  8 10:26` back when the server was named `skohub.lobid.org`.
I _could_ rewrite all those files, but not sure of consequences.
I assume the servers name will be correct for all newer vocabs, right?
Question is, if you rather want to rebuild it - is this even possible?

**Comment by acka47** [comment]
Ah, ok. I triggered a rebuild. It is fixed now in Hochsculfaechersystematik. However,  Raphaëlle  pointed to another vocab that was built yesterday, see e.g. https://skohub.io/hbz/vocabs-edu/heads/master/w3id.org/class/esc/n03.html. I also rebuit that one but it still points to skohub.lobid.org. Strange.

**Comment by dr0i** [comment]
Yeah, you're right: in the `.env` it's said:` BUILD_URL=https://skohub.lobid.org/build/`.
Changed that, please rebuild @acka47 .

**Comment by acka47** [comment]
Now it is fixed, see inbox links at https://w3id.org/class/esc/n06 & https://w3id.org/kim/hochschulfaechersystematik/n1. Closing.
