### ISSUE TITLE
"followers" and "inbox" keys are not in JSON-LD context

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-vocabs#87]
See e.g. https://skohub.io/hbz/vocabs-edu/heads/master/w3id.org/class/esc/n0322.json:

```json
{
  "id":"https://w3id.org/class/esc/n0322",
  "type":"Concept",
  "followers":"https://skohub.io/followers?subject=hbz%2Fvocabs-edu%2Fheads%2Fmaster%2Fw3id.org%2Fclass%2Fesc%2Fn0322",
  "inbox":"https://skohub.io/inbox?actor=hbz%2Fvocabs-edu%2Fheads%2Fmaster%2Fw3id.org%2Fclass%2Fesc%2Fn0322",
  "prefLabel":{
    "en":"Library, information and archival studies"
  },
  "notation":[
    "0322"
  ],
  "broader":{
    "id":"https://w3id.org/class/esc/n032",
    "prefLabel":{
      "en":"Journalism and information"
    }
  },
  "inScheme":{
    "id":"https://w3id.org/class/esc/scheme",
    "title":{
      "en":"Educational Subjects Classification"
    }
  },
  "@context":{
    "id":"@id",
    "type":"@type",
    "@vocab":"http://www.w3.org/2004/02/skos/core#",
    "xsd":"http://www.w3.org/2001/XMLSchema#",
    "dct":"http://purl.org/dc/terms/",
    "schema":"http://schema.org/",
    "vann":"http://purl.org/vocab/vann/",
    "title":{
      "@id":"dct:title",
      "@container":"@language"
    },
    "description":{
      "@id":"dct:description",
      "@container":"@language"
    },
    "issued":{
      "@id":"dct:issued",
      "@type":"xsd:date"
    },
    "created":{
      "@id":"dct:created",
      "@type":"xsd:date"
    },
    "modified":{
      "@id":"dct:modified",
      "@type":"xsd:date"
    },
    "creator":"dct:creator",
    "publisher":"dct:publisher",
    "preferredNamespacePrefix":"vann:preferredNamespacePrefix",
    "preferredNamespaceUri":"vann:preferredNamespaceUri",
    "isBasedOn":"schema:isBasedOn",
    "source":"dct:source",
    "prefLabel":{
      "@container":"@language"
    },
    "definition":{
      "@container":"@language"
    },
    "scopeNote":{
      "@container":"@language"
    },
    "note":{
      "@container":"@language"
    },
    "notation":{
      "@container":"@set"
    },
    "narrower":{
      "@container":"@set"
    },
    "narrowerTransitive":{
      "@container":"@set"
    },
    "broaderTransitive":{
      "@container":"@set"
    }
  }
}
```

**Comment by acka47** [comment]
Taking a look at https://skohub.io/hbz/vocabs-edu/heads/master/w3id.org/class/esc/n0322.jsonas, I notice that the same `followers` and `inbox` statements can already be found there. Thus, the question: Do we need this redundancy or could the statements be removed from the JSON/SKOS representation?

**Comment by dr0i** [comment]
The last question remains to be unanswered, so I reopened this issue.
Also, the embedded context is not automatically updated for e.g. https://skohub.io/hbz/vocabs-edu/heads/master/w3id.org/class/esc/n0322.json . Thus, if I understand correctly, all vocabs must be rebuild. How triggers this?

**Comment by literarymachine** [comment]
> Also, the embedded context is not automatically updated for e.g. https://skohub.io/hbz/vocabs-edu/heads/master/w3id.org/class/esc/n0322.json . Thus, if I understand correctly, all vocabs must be rebuild.

Maybe we should consider referencing a remote context instead of embedding it? That way it could be updated without the need to rebuild vocab data.

**Comment by acka47** [comment]
> Maybe we should consider referencing a remote context instead of embedding it? That way it could be updated without the need to rebuild vocab data.

Yes, we should definitely do this.

**Comment by acka47** [comment]
I opened a new issue for the remote context, see https://github.com/hbz/skohub-vocabs/issues/89. I will now close this issue.
